### ISSUE TITLE
Cannot load pretrained weight

### ISSUE THREAD

**Issue by JasiRose** [zhang-tao-whu/DVIS_Plus#11]
Dear Mr. Zhang,
Firstly, I want to thank you for your efforts in developing and maintaining DIVS_Plus.

I'm writing to report an issue I encountered while trying to load the model weights from the repository. Specifically, when I tried to retrain Segmenter on the VSPW dataset, the weights for pretrained Segmenter `Mask2Former(panoptic) ViT-L` seem to be problematic. I've successfully loaded other weights provided in the repository, but when attempting to load this particular one, I receive the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/anaconda3/envs/vspw/lib/python3.8/site-packages/torch/serialization.py", line 600, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/root/anaconda3/envs/vspw/lib/python3.8/site-packages/torch/serialization.py", line 242, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
```

I've tried downloading the file multiple times from both `baidupan` and `HuggingFace` to rule out download corruption. Could you please check if the model weight file for `Mask2Former(panoptic) ViT-L` is uploaded correctly, or if there's a known issue with this file? Any guidance on how to resolve this issue would be greatly appreciated.

**Comment by zhang-tao-whu** [comment]
Sorry for the delayed response. It appears that the pre-trained weights are indeed corrupted. I'll need to retrain them, which may take some time.

**Comment by zhang-tao-whu** [comment]
If you have a spare GPU available, you can also try training it yourself. [config](https://github.com/zhang-tao-whu/Mask2Former/blob/main/configs/coco/panoptic-segmentation/vit_adapter/maskformer2_vitl_adapter_dinov2_bs16_50ep.yaml)
