### ISSUE TITLE
KeyError: 'Non-existent config key: MODEL.FC_CLIP'

### ISSUE THREAD

**Issue by BHM-Bob** [zhang-tao-whu/DVIS_Plus#24]
感谢您的工作，我对视频分割领域不熟，只想用您的工作作为一个工具。在配置好环境后运行
```bash
python demo_video/demo_long_video.py --config-file configs/open_vocabulary/R50/DVIS_Offline_zero_shot_r50.yaml --input example/30s_frames --output example/30s_frames_out/ --windows_size 300 --opts MODEL.WEIGHTS models/ov_offline_zero_shot_r50.pt
```
出现错误：`KeyError: 'Non-existent config key: MODEL.FC_CLIP'`

具体报错：
```
Traceback (most recent call last):
  File "xxx/DVIS_Plus/DVIS_Plus/demo_video/demo_long_video.py", line 93, in <module>
    cfg = setup_cfg(args)
          ^^^^^^^^^^^^^^^
  File "xxx/DVIS_Plus/DVIS_Plus/demo_video/demo_long_video.py", line 43, in setup_cfg
    cfg.merge_from_file(args.config_file)
  File "/home/pcmd37/anaconda3/envs/torch/lib/python3.12/site-packages/detectron2/config/config.py", line 69, in merge_from_file
    self.merge_from_other_cfg(loaded_cfg)
  File "/home/pcmd37/anaconda3/envs/torch/lib/python3.12/site-packages/fvcore/common/config.py", line 132, in merge_from_other_cfg
    return super().merge_from_other_cfg(cfg_other)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pcmd37/anaconda3/envs/torch/lib/python3.12/site-packages/yacs/config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "/home/pcmd37/anaconda3/envs/torch/lib/python3.12/site-packages/yacs/config.py", line 477, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/home/pcmd37/anaconda3/envs/torch/lib/python3.12/site-packages/yacs/config.py", line 491, in _merge_a_into_b
    raise KeyError("Non-existent config key: {}".format(full_key))
KeyError: 'Non-existent config key: MODEL.FC_CLIP'
```

请问我哪里做错了？

**Comment by BHM-Bob** [comment]
好像选错config了
